// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package nettrace

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type traceAddrInfo struct {
	Ip4    uint32
	Port   uint16
	Family uint16
}

type traceFdKey struct {
	Pid uint32
	Fd  int32
}

type traceIoState struct {
	Fd   int32
	Op   uint8
	Pad1 uint8
	Pad2 uint16
	Addr traceAddrInfo
}

// loadTrace returns the embedded CollectionSpec for trace.
func loadTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load trace: %w", err)
	}

	return spec, err
}

// loadTraceObjects loads trace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceObjects
//	*tracePrograms
//	*traceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceSpecs struct {
	traceProgramSpecs
	traceMapSpecs
}

// traceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceProgramSpecs struct {
	TraceEnterConnect  *ebpf.ProgramSpec `ebpf:"trace_enter_connect"`
	TraceEnterRecvfrom *ebpf.ProgramSpec `ebpf:"trace_enter_recvfrom"`
	TraceEnterRecvmsg  *ebpf.ProgramSpec `ebpf:"trace_enter_recvmsg"`
	TraceEnterSendmsg  *ebpf.ProgramSpec `ebpf:"trace_enter_sendmsg"`
	TraceEnterSendto   *ebpf.ProgramSpec `ebpf:"trace_enter_sendto"`
	TraceExitConnect   *ebpf.ProgramSpec `ebpf:"trace_exit_connect"`
	TraceExitRecvfrom  *ebpf.ProgramSpec `ebpf:"trace_exit_recvfrom"`
	TraceExitRecvmsg   *ebpf.ProgramSpec `ebpf:"trace_exit_recvmsg"`
	TraceExitSendmsg   *ebpf.ProgramSpec `ebpf:"trace_exit_sendmsg"`
	TraceExitSendto    *ebpf.ProgramSpec `ebpf:"trace_exit_sendto"`
}

// traceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	FdAddr         *ebpf.MapSpec `ebpf:"fd_addr"`
	PendingConnect *ebpf.MapSpec `ebpf:"pending_connect"`
	PendingIo      *ebpf.MapSpec `ebpf:"pending_io"`
}

// traceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceObjects struct {
	tracePrograms
	traceMaps
}

func (o *traceObjects) Close() error {
	return _TraceClose(
		&o.tracePrograms,
		&o.traceMaps,
	)
}

// traceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	FdAddr         *ebpf.Map `ebpf:"fd_addr"`
	PendingConnect *ebpf.Map `ebpf:"pending_connect"`
	PendingIo      *ebpf.Map `ebpf:"pending_io"`
}

func (m *traceMaps) Close() error {
	return _TraceClose(
		m.Events,
		m.FdAddr,
		m.PendingConnect,
		m.PendingIo,
	)
}

// tracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracePrograms struct {
	TraceEnterConnect  *ebpf.Program `ebpf:"trace_enter_connect"`
	TraceEnterRecvfrom *ebpf.Program `ebpf:"trace_enter_recvfrom"`
	TraceEnterRecvmsg  *ebpf.Program `ebpf:"trace_enter_recvmsg"`
	TraceEnterSendmsg  *ebpf.Program `ebpf:"trace_enter_sendmsg"`
	TraceEnterSendto   *ebpf.Program `ebpf:"trace_enter_sendto"`
	TraceExitConnect   *ebpf.Program `ebpf:"trace_exit_connect"`
	TraceExitRecvfrom  *ebpf.Program `ebpf:"trace_exit_recvfrom"`
	TraceExitRecvmsg   *ebpf.Program `ebpf:"trace_exit_recvmsg"`
	TraceExitSendmsg   *ebpf.Program `ebpf:"trace_exit_sendmsg"`
	TraceExitSendto    *ebpf.Program `ebpf:"trace_exit_sendto"`
}

func (p *tracePrograms) Close() error {
	return _TraceClose(
		p.TraceEnterConnect,
		p.TraceEnterRecvfrom,
		p.TraceEnterRecvmsg,
		p.TraceEnterSendmsg,
		p.TraceEnterSendto,
		p.TraceExitConnect,
		p.TraceExitRecvfrom,
		p.TraceExitRecvmsg,
		p.TraceExitSendmsg,
		p.TraceExitSendto,
	)
}

func _TraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trace_bpfel.o
var _TraceBytes []byte
