// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package filetrace

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type traceOpenState struct {
	Flags    uint32
	Filename [256]int8
}

// loadTrace returns the embedded CollectionSpec for trace.
func loadTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load trace: %w", err)
	}

	return spec, err
}

// loadTraceObjects loads trace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceObjects
//	*tracePrograms
//	*traceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceSpecs struct {
	traceProgramSpecs
	traceMapSpecs
}

// traceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceProgramSpecs struct {
	TraceEnterOpenat  *ebpf.ProgramSpec `ebpf:"trace_enter_openat"`
	TraceEnterOpenat2 *ebpf.ProgramSpec `ebpf:"trace_enter_openat2"`
	TraceExitOpenat   *ebpf.ProgramSpec `ebpf:"trace_exit_openat"`
	TraceExitOpenat2  *ebpf.ProgramSpec `ebpf:"trace_exit_openat2"`
}

// traceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	PendingOpen *ebpf.MapSpec `ebpf:"pending_open"`
}

// traceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceObjects struct {
	tracePrograms
	traceMaps
}

func (o *traceObjects) Close() error {
	return _TraceClose(
		&o.tracePrograms,
		&o.traceMaps,
	)
}

// traceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	PendingOpen *ebpf.Map `ebpf:"pending_open"`
}

func (m *traceMaps) Close() error {
	return _TraceClose(
		m.Events,
		m.PendingOpen,
	)
}

// tracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracePrograms struct {
	TraceEnterOpenat  *ebpf.Program `ebpf:"trace_enter_openat"`
	TraceEnterOpenat2 *ebpf.Program `ebpf:"trace_enter_openat2"`
	TraceExitOpenat   *ebpf.Program `ebpf:"trace_exit_openat"`
	TraceExitOpenat2  *ebpf.Program `ebpf:"trace_exit_openat2"`
}

func (p *tracePrograms) Close() error {
	return _TraceClose(
		p.TraceEnterOpenat,
		p.TraceEnterOpenat2,
		p.TraceExitOpenat,
		p.TraceExitOpenat2,
	)
}

func _TraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trace_bpfel.o
var _TraceBytes []byte
