// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package exectrace

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type traceArgvCache struct {
	Filename [256]int8
	Argc     uint32
	Argv     [20][256]int8
}

// loadTrace returns the embedded CollectionSpec for trace.
func loadTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load trace: %w", err)
	}

	return spec, err
}

// loadTraceObjects loads trace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceObjects
//	*tracePrograms
//	*traceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceSpecs struct {
	traceProgramSpecs
	traceMapSpecs
}

// traceSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceProgramSpecs struct {
	TraceEnterExecve   *ebpf.ProgramSpec `ebpf:"trace_enter_execve"`
	TraceEnterExecveat *ebpf.ProgramSpec `ebpf:"trace_enter_execveat"`
	TraceSchedExec     *ebpf.ProgramSpec `ebpf:"trace_sched_exec"`
}

// traceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceMapSpecs struct {
	ArgvCacheMap *ebpf.MapSpec `ebpf:"argv_cache_map"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	Scratch      *ebpf.MapSpec `ebpf:"scratch"`
}

// traceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceObjects struct {
	tracePrograms
	traceMaps
}

func (o *traceObjects) Close() error {
	return _TraceClose(
		&o.tracePrograms,
		&o.traceMaps,
	)
}

// traceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceMaps struct {
	ArgvCacheMap *ebpf.Map `ebpf:"argv_cache_map"`
	Events       *ebpf.Map `ebpf:"events"`
	Scratch      *ebpf.Map `ebpf:"scratch"`
}

func (m *traceMaps) Close() error {
	return _TraceClose(
		m.ArgvCacheMap,
		m.Events,
		m.Scratch,
	)
}

// tracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracePrograms struct {
	TraceEnterExecve   *ebpf.Program `ebpf:"trace_enter_execve"`
	TraceEnterExecveat *ebpf.Program `ebpf:"trace_enter_execveat"`
	TraceSchedExec     *ebpf.Program `ebpf:"trace_sched_exec"`
}

func (p *tracePrograms) Close() error {
	return _TraceClose(
		p.TraceEnterExecve,
		p.TraceEnterExecveat,
		p.TraceSchedExec,
	)
}

func _TraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed trace_bpfel.o
var _TraceBytes []byte
